use dicom_core::header::Header;
use dicom_core::{DataElement, PrimitiveValue};
use dicom_object::DefaultDicomObject;
use dicom_object::mem::InMemElement;
use std::borrow::Cow;

use crate::actions::ProcessElement;
use crate::actions::errors::ActionError;
use crate::actions::utils::{is_empty_element, truncate_to};
use crate::config::Config;
use crate::config::uid_root::UidRoot;
use crate::hasher::HashFn;

const UID_MAX_LENGTH: usize = 64;

/// Action that anonymizes DICOM UID (Unique Identifier) values by generating new UIDs from hashes.
///
/// This action replaces UID values with new UIDs generated by hashing the original UID
/// and prepending an optional UID root. The resulting UIDs maintain uniqueness
/// while removing any identifying information from the original UIDs.
#[derive(Debug, Clone, PartialEq)]
pub struct HashUID;

impl HashUID {
    fn anonymize(
        &self,
        hash_fn: HashFn,
        uid: &str,
        uid_root: &UidRoot,
    ) -> Result<String, ActionError> {
        // Idempotency: a UID that already carries the configured root prefix was
        // derived from this configuration before and is passed through unchanged,
        // so that de-identifying an already de-identified file is a no-op for UIDs.
        let prefix = uid_root.as_prefix();
        if !prefix.is_empty() && uid.starts_with(prefix.as_str()) {
            return Ok(uid.to_string());
        }

        let anonymized_uid_as_number = hash_fn(uid)?;
        let anonymized_uid = anonymized_uid_as_number.to_string();
        let extra = if anonymized_uid.starts_with("0") {
            "9"
        } else {
            ""
        };
        let new_uid = format!("{}{}{}", uid_root.as_prefix(), extra, anonymized_uid);
        let result = truncate_to(UID_MAX_LENGTH, &new_uid);

        Ok(result)
    }
}

impl ProcessElement for HashUID {
    fn process<'a>(
        &'a self,
        config: &Config,
        _obj: &DefaultDicomObject,
        elem: &'a InMemElement,
    ) -> Result<Option<Cow<'a, InMemElement>>, ActionError> {
        if is_empty_element(elem) {
            return Ok(Some(Cow::Borrowed(elem)));
        }

        let hash_fn = config.get_hash_fn();
        let uid_root = match config.get_uid_root() {
            Some(uid_root) => uid_root,
            None => &UidRoot("".into()),
        };
        let elem_value = elem.value().string()?;
        // Normalize padding before hashing: DICOM UI values may carry trailing
        // space or NUL padding bytes (e.g. odd-length values). The canonical
        // cross-implementation derivation hashes the trimmed UID so that all
        // de-identification gates agree on the derived UID.
        let elem_value = elem_value.trim_matches(|c: char| c.is_whitespace() || c == '\0');
        let anonymized_value = self.anonymize(hash_fn, elem_value, uid_root)?;

        let new_elem = DataElement::new::<PrimitiveValue>(
            elem.tag(),
            elem.vr(),
            PrimitiveValue::from(anonymized_value),
        );
        Ok(Some(Cow::Owned(new_elem)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use dicom_core::header::HasLength;
    use dicom_core::value::Value;
    use dicom_core::{VR, header};
    use dicom_object::FileDicomObject;
    use num_bigint::BigInt;

    use crate::config::builder::ConfigBuilder;
    use crate::hasher::blake3_hash_fn;
    use crate::tags;
    use crate::test_utils::make_file_meta;

    #[test]
    fn test_process() {
        let mut obj = FileDicomObject::new_empty_with_meta(make_file_meta());
        let elem = InMemElement::new(
            tags::STUDY_INSTANCE_UID,
            VR::UI,
            Value::from("12.34.56.78.9"),
        );
        obj.put(elem.clone());

        let action_struct = HashUID;
        let config = Config::default();

        let processed = action_struct.process(&config, &obj, &elem).unwrap();
        // make sure it's cut off at the max length for VR UI (i.e. 64)
        assert_eq!(
            processed.unwrap().into_owned().value().length(),
            header::Length(64)
        );
    }

    #[test]
    fn test_process_with_uid_root() {
        let mut obj = FileDicomObject::new_empty_with_meta(make_file_meta());
        let elem = InMemElement::new(
            tags::STUDY_INSTANCE_UID,
            VR::UI,
            Value::from("12.34.56.78.9"),
        );
        obj.put(elem.clone());

        let action_struct = HashUID;
        let uid_root = "9999".parse().unwrap();
        let config = ConfigBuilder::new().uid_root(uid_root).build();

        let processed = action_struct.process(&config, &obj, &elem).unwrap();
        let processed = processed.unwrap();
        let processed = processed.into_owned();
        assert_eq!(processed.value().length(), header::Length(64));
        let processed_value: String = processed.value().to_str().unwrap().into();
        assert!(processed_value.starts_with("9999."));
    }

    #[test]
    fn test_process_with_empty_element() {
        let mut obj = FileDicomObject::new_empty_with_meta(make_file_meta());
        let elem = InMemElement::new(
            tags::STUDY_INSTANCE_UID,
            VR::UI,
            Value::Primitive(PrimitiveValue::Empty),
        );
        obj.put(elem.clone());

        let action_struct = HashUID;
        let config = Config::default();

        let processed = action_struct.process(&config, &obj, &elem).unwrap();
        assert_eq!(processed.unwrap().into_owned(), elem);
    }

    #[test]
    fn test_anonymize_without_prefix() {
        let uid = "1.2.3.4.5";
        let uid_root = "".parse().unwrap();
        let hash_fn = blake3_hash_fn;
        let action_struct = HashUID;
        let result = action_struct.anonymize(hash_fn, uid, &uid_root);
        let result = result.unwrap();
        assert_eq!(result.len(), 64);
        assert!(!result.contains("."));
    }

    #[test]
    fn test_anonymize_with_prefix() {
        let uid = "1.2.3.4.5";
        let prefix = "2.16.840";
        let uid_root = prefix.parse().unwrap();
        let hash_fn = blake3_hash_fn;
        let action_struct = HashUID;
        let result = action_struct.anonymize(hash_fn, uid, &uid_root);
        let result = result.unwrap();
        assert_eq!(result.len(), 64);
        assert!(result.starts_with("2.16.840."));
    }

    #[test]
    fn test_anonymize_with_empty_prefix() {
        let uid = "1.2.3.4.5";
        let prefix = "";
        let uid_root = prefix.parse().unwrap();
        let hash_fn = blake3_hash_fn;
        let action_struct = HashUID;
        let result = action_struct.anonymize(hash_fn, uid, &uid_root);
        let result = result.unwrap();
        assert_eq!(result.len(), 64);
        assert!(!result.contains("."));
    }

    #[test]
    fn test_anonymize_with_prefix_with_dot() {
        let uid = "1.2.3.4.5";
        let prefix = "2.16.840.";
        let uid_root = prefix.parse().unwrap();
        let hash_fn = blake3_hash_fn;
        let action_struct = HashUID;
        let result = action_struct.anonymize(hash_fn, uid, &uid_root);
        let result = result.unwrap();
        assert_eq!(result.len(), 64);
        assert!(result.starts_with("2.16.840."));
        assert!(!result.starts_with("2.16.840.."));
    }

    #[test]
    fn test_anonymize_with_long_uid() {
        let uid = "1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.18.19.20.21.22.23.24.25.26.27";
        let prefix = "2.16.840";
        let uid_root = prefix.parse().unwrap();
        let hash_fn = blake3_hash_fn;
        let action_struct = HashUID;
        let result = action_struct.anonymize(hash_fn, uid, &uid_root);
        let result = result.unwrap();
        assert_eq!(result.len(), 64);
        assert!(result.starts_with("2.16.840."));
    }

    #[test]
    fn test_anonymize_with_non_zero_first_digit() {
        let uid = "1.2.3.4.5";
        let prefix = "2.16.840";
        let uid_root = prefix.parse().unwrap();
        let hash_fn =
            |_input: &str| -> Result<BigInt, crate::hasher::Error> { Ok(BigInt::from(123456789)) };
        let action_struct = HashUID;
        let result = action_struct.anonymize(hash_fn, uid, &uid_root);
        assert_eq!(result.unwrap(), "2.16.840.123456789");
    }

    /// Golden vectors for the canonical SHA-256 UID derivation shared with the C#
    /// (fo-dicom backstop) and Python (Presidio) de-identification gates. These
    /// must never change without a coordinated cross-implementation release.
    #[test]
    fn test_anonymize_sha256_golden_vectors() {
        let uid_root = "2.25.3501920042.100".parse().unwrap();
        let hash_fn = crate::hasher::sha256_hash_fn;
        let action = HashUID;

        assert_eq!(
            action.anonymize(hash_fn, "1.2.3.4.5", &uid_root).unwrap(),
            "2.25.3501920042.100.83554103981997929853173016752638312087386577"
        );
        assert_eq!(
            action.anonymize(hash_fn, "1.2.3.4.5.6", &uid_root).unwrap(),
            "2.25.3501920042.100.11565063281463045692094511316009653451771902"
        );
        assert_eq!(
            action.anonymize(hash_fn, "1.2.3.4.5.6.7", &uid_root).unwrap(),
            "2.25.3501920042.100.86134114536617455996661681892008515039411444"
        );
    }

    /// The `process` entry point must trim padding (trailing space or NUL) before
    /// hashing so that the derived UID depends on the logical UID only.
    #[test]
    fn test_process_sha256_trims_padding() {
        let mut obj = FileDicomObject::new_empty_with_meta(make_file_meta());
        let elem = InMemElement::new(
            tags::STUDY_INSTANCE_UID,
            VR::UI,
            Value::from("1.2.3.4.5\0"),
        );
        obj.put(elem.clone());

        let config = ConfigBuilder::new()
            .uid_root("2.25.3501920042.100".parse().unwrap())
            .hash_algorithm(crate::config::HashAlgorithm::Sha256)
            .build();

        let action = HashUID;
        let processed = action.process(&config, &obj, &elem).unwrap().unwrap();
        assert_eq!(
            processed.into_owned().value().to_str().unwrap(),
            "2.25.3501920042.100.83554103981997929853173016752638312087386577"
        );
    }

    /// A value that is already canonical (starts with the canonical root) is a
    /// fixed point: hashing a derived UID again yields the same UID.
    #[test]
    fn test_process_sha256_is_idempotent() {
        let canonical = "2.25.3501920042.100.83554103981997929853173016752638312087386577";
        let mut obj = FileDicomObject::new_empty_with_meta(make_file_meta());
        let elem = InMemElement::new(
            tags::STUDY_INSTANCE_UID,
            VR::UI,
            Value::from(canonical),
        );
        obj.put(elem.clone());

        let config = ConfigBuilder::new()
            .uid_root("2.25.3501920042.100".parse().unwrap())
            .hash_algorithm(crate::config::HashAlgorithm::Sha256)
            .build();

        let action = HashUID;
        let processed = action.process(&config, &obj, &elem).unwrap().unwrap();
        assert_eq!(
            processed.into_owned().value().to_str().unwrap(),
            canonical
        );
    }
}
